services: 

  # admin:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  fastapi-db:
    container_name: fastapi-db
    build:
      context: /home/kyoko/code/fastAPI-proj/docker/
      dockerfile: Dockerfile
    image: postgres:18.1
    shm_size: 1024mb
    restart: always
    working_dir: /docker
    ports:
      - 5432:5432
    volumes:
      - /home/kyoko/code/fastAPI-proj/docker/:/docker
    environment:
      POSTGRES_PASSWORD: party
    stdin_open: true
    tty: true
  